Add missing Semigroup instances
This change fixes the following errors:

  Text/PrettyPrint/Final.hs:101:10: error: [GHC-39999]
      • No instance for ‘Semigroup (POut w ann)’
          arising from the superclasses of an instance declaration
      • In the instance declaration for ‘Monoid (POut w ann)’
      |
  101 | instance Monoid (POut w ann) where